//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RewardsForYou.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeMissionEnded
    {
        public int UserID { get; set; }
        public int MissionID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Missions Missions { get; set; }
        public virtual Users Users { get; set; }
    }
}
