//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RewardsForYou.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeRewardsTakes
    {
        public int NoticeRewardsTakesID { get; set; }
        public int UserID { get; set; }
        public int UsersRewardsID { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public int ManagerID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual UsersRewards UsersRewards { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
